import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { userImage, productImage, productTitle, productColor } = await req.json();
    
    if (!userImage || !productImage) {
      throw new Error('Both userImage and productImage are required');
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    const color = productColor || 'White';
    
    console.log(`Generating mockup for ${productTitle} in color: ${color}`);

    // Optimized prompt for accurate color, texture, and realistic mockup generation
    const prompt = `Create a photorealistic product mockup for e-commerce.

PRODUCT SPECIFICATION:
- Product: ${productTitle}
- Color: ${color.toUpperCase()} (MANDATORY - override any reference image color)

IMAGE INPUTS:
1. FIRST IMAGE = Design artwork to print (use EXACTLY as-is, no modifications)
2. SECOND IMAGE = Product shape/style reference ONLY (IGNORE its color completely)

MANDATORY COLOR RULE:
Generate the ${productTitle} in ${color.toUpperCase()} fabric/material color.
- Do NOT copy the color from the reference image
- The entire product surface must be ${color}
- This color will match what Printify produces

DESIGN APPLICATION:
- Print area placement:
  * T-shirts/Hoodies: Center chest, proportional to garment
  * Mugs: Wrap naturally around cylindrical surface
  * Tote bags: Center front panel
  * Greeting cards: Center front face
- Apply the design with realistic:
  * Fabric texture (cotton weave for apparel, smooth for mugs)
  * Natural wrinkles and folds where fabric bends
  * Proper perspective distortion following the product contours
  * Soft shadows where design meets fabric

LIGHTING & REALISM:
- Consistent soft studio lighting from upper-left
- Subtle shadows under the product
- Design should appear screen-printed/heat-transferred, not floating
- Colors should integrate with the ${color} base naturally

OUTPUT: Professional-quality mockup of a ${color} ${productTitle} with the exact design printed on it.`;
    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image-preview',
        messages: [
          {
            role: 'user',
            content: [
              {
                type: 'text',
                text: prompt
              },
              {
                type: 'image_url',
                image_url: {
                  url: userImage
                }
              },
              {
                type: 'image_url',
                image_url: {
                  url: productImage
                }
              }
            ]
          }
        ],
        modalities: ['image', 'text']
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Lovable AI error:', errorText);
      
      if (response.status === 429) {
        throw new Error('Rate limit exceeded. Please try again in a moment.');
      }
      if (response.status === 402) {
        throw new Error('AI credits exhausted. Please add credits to continue.');
      }
      
      throw new Error(`AI service error: ${response.status}`);
    }

    const data = await response.json();
    console.log('AI response received');

    const generatedImageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!generatedImageUrl) {
      throw new Error('No image generated by AI');
    }

    return new Response(
      JSON.stringify({ mockupUrl: generatedImageUrl }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  } catch (error) {
    console.error('Error generating mockup:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Failed to generate mockup',
        details: error instanceof Error ? error.stack : undefined
      }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});
